resources:
  - name: buildinfoGoGit
    type: GitRepo
    configuration:
      path: gailazar300/build-info-go
      branches:
        include: repo21-release
      gitProvider: gai_github

pipelines:
  - name: release_build_info_go
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: releases-docker.jfrog.io/jfrog-ecosystem-integration-env
            tag: 1.5.0
      environmentVariables:
        readOnly:
          NEXT_VERSION: 0.0.0

    steps:
      - name: Release
        type: Bash
        configuration:
          inputResources:
            - name: buildinfoGoGit
          integrations:
            - name: il_automation
            - name: entplus_deployer
        execution:
          onExecute:
            - cd $res_buildinfoGoGit_resourcePath

            # Set env
            - export CI=true
            - export JFROG_CLI_BUILD_NAME=ecosystem-build-info-go-release
            - export JFROG_CLI_BUILD_NUMBER=$run_number
            - export JFROG_CLI_BUILD_PROJECT=ecosys

            # Make sure version provided
            - echo "Checking variables"
            - test -n "$NEXT_VERSION" -a "$NEXT_VERSION" != "0.0.0"

            # Configure JFrog CLI
            - curl -fL https://getcli.jfrog.io | bash -s v2 && chmod +x jfrog
            - ./jfrog c add internal --url=$int_entplus_deployer_url --user=$int_entplus_deployer_user --password=int_entplus_deployer_apikey

            # Build and upload
            - chmod +x release/build.sh
            - sh release/build.sh "$NEXT_VERSION"

            # Distribute release bundle
            - ./jfrog ds rbc "build-info-go" $NEXT_VERSION --spec="release/specs/bi-rbc-spec.json" --spec-vars="VERSION=$NEXT_VERSION" --sign
            #- ./jfrog ds rbd "build-info-go" $NEXT_VERSION --site=releases.jrog.io
